services:
  app:
    image: simple-task-planner.jar
    hostname: localhost
    expose:
      - 8080
    ports:
      - 8080:8080
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/compose-postgres
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: compose-postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LOCAL_PORT: 6868
      SPRING_DOCKER_PORT: 8080

  db:
    image: postgres:15
    ports:
      - 5432
    container_name: db
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres